env:
  BUILD_CACHE_PATH: /spack-stack/build-cache-new-spack-v1
  SOURCE_CACHE_PATH: /spack-stack/source-cache
jobs:
  ubuntu-ci-c6a-x86_64-gnu-build:
    steps:
    - name: checkout
      run: |
        echo Cloning repo to $PWD
        git clone https://github.com/${{ inputs.gh_org }}/${{ inputs.gh_repo }}
        cd ${{ inputs.gh_repo }}
        git checkout ${{ inputs.gh_branch }}
    - name: prepare-directories
      run: |
        # DH* REVERT ME AFTER MERGE
        mkdir -pv ${BUILD_CACHE_PATH}
        mkdir -pv ${SOURCE_CACHE_PATH}
    - name: create-buildcache
      run: |
        # Get day of week to decide whether to use build caches or not
        DOW=$(date +%u)
        # Monday is 1 ... Sunday is 7
        if [[ $DOW == 7 ]]; then
          export USE_BINARY_CACHE=false
          echo "Ignore existing binary cache for creating buildcache environment"
        else
          export USE_BINARY_CACHE=true
          echo "Use existing binary cache for creating buildcache environment"
        fi

        # Set up spack-stack
        cd ${{ inputs.gh_repo }}
        source ./setup.sh

        declare -a TEMPLATES=("unified-dev" "skylab-dev" "cylc-dev" "neptune-dev")
        for TEMPLATE in "${TEMPLATES[@]}"; do
          if [[ "${TEMPLATE}" == *"unified-dev"* ]]; then
            export ENVNAME=ue-gcc-11.4.0-buildcache
          elif [[ "${TEMPLATE}" == *"skylab-dev"* ]]; then
            export ENVNAME=se-gcc-11.4.0-buildcache
          elif [[ "${TEMPLATE}" == *"cylc-dev"* ]]; then
            export ENVNAME=ce-gcc-11.4.0-buildcache
          elif [[ "${TEMPLATE}" == *"neptune-dev"* ]]; then
            export ENVNAME=ne-gcc-11.4.0-buildcache
          fi
          echo "Creating environment ${ENVNAME} from template ${TEMPLATE}"

          export ENVDIR=$PWD/envs/${ENVNAME}
          spack stack create env --site linux.default --template ${TEMPLATE} --name ${ENVNAME} --compiler gcc
          spack env activate ${ENVDIR}

          # Turn off variant "adp" for neptune-dev (NRL internal only)
          if [[ "${TEMPLATE}" == *"neptune-dev"* ]]; then
            sed -i 's/+adp/~adp/g' ${ENVDIR}/spack.yaml
          fi

          unset SPACK_DISABLE_LOCAL_CONFIG
          export SPACK_SYSTEM_CONFIG_PATH="${ENVDIR}/site"

          # Find external packages
          spack external find --scope system \
              --exclude bison --exclude openssl \
              --exclude curl --exclude python \
              --exclude meson
          spack external find --scope system grep
          spack external find --scope system sed
          spack external find --scope system perl
          spack external find --scope system wget
          spack external find --scope system texlive
          spack external find --scope system mysql

          # Find compilers
          spack compiler find --scope system

          export SPACK_DISABLE_LOCAL_CONFIG=true
          unset SPACK_SYSTEM_CONFIG_PATH

          # For buildcaches
          spack config add config:install_tree:padded_length:200

          # Set compiler and MPI specs
          spack config add "packages:mpi:require:['openmpi@5.0.8']"
          spack config add "packages:all:prefer:['%gcc']"

          # Add additional variants for MET packages, different from config/common/packages.yaml
          spack config add "packages:met:variants:+python +grib2 +graphics +lidar2nc +modis"

          # Concretize and check for duplicates
          spack concretize --force --fresh 2>&1 | tee log.concretize.${ENVNAME}
          ${SPACK_STACK_DIR}/util/show_duplicate_packages.py -i fms -i crtm -i crtm-fix -i esmf -i mapl -i py-cython -i neptune-env

          # Add and update source cache
          spack mirror add local-source file://${SOURCE_CACHE_PATH}/
          spack mirror create -a -d ${SOURCE_CACHE_PATH}/

          # Add binary cache if requested
          if [ "$USE_BINARY_CACHE" = true ] ; then
            set +e
            spack mirror add local-binary file://${BUILD_CACHE_PATH}/
            spack buildcache update-index local-binary
            set -e
            echo "Packages in spack binary cache:"
            spack buildcache list
          fi

          # Break installation up in pieces and create build caches in between
          # This allows us to "spin up" builds that altogether take longer than
          # six hours, and/or fail later in the build process.

          if [[ "${TEMPLATE}" == *"unified-dev"* || "${TEMPLATE}" == *"skylab-dev"* ]]; then
            # base-env
            echo "base-env ..."
            spack install --fail-fast --source --no-check-signature base-env 2>&1 | tee log.install.${ENVNAME}.base-env
            spack buildcache create -u local-binary base-env
            # jedi-base-env
            echo "jedi-base-env ..."
            spack install --fail-fast --source --no-check-signature jedi-base-env 2>&1 | tee log.install.${ENVNAME}.jedi-base-env
            spack buildcache create -u local-binary jedi-base-env
            # jedi-ufs-env
            echo "jedi-ufs-env ..."
            spack install --fail-fast --source --no-check-signature jedi-ufs-env 2>&1 | tee log.install.${ENVNAME}.jedi-ufs-env
            spack buildcache create -u local-binary jedi-ufs-env
          elif [[ "${TEMPLATE}" == *"neptune-dev"* ]]; then
            # base-env
            echo "base-env ..."
            spack install --fail-fast --source --no-check-signature base-env 2>&1 | tee log.install.${ENVNAME}.base-env
            spack buildcache create -u local-binary base-env
            # neptune-python-env
            echo "neptune-env ..."
            spack install --fail-fast --source --no-check-signature neptune-python-env 2>&1 | tee log.install.${ENVNAME}.neptune-env
            spack buildcache create -u local-binary neptune-python-env
          fi

          # the rest
          echo "${TEMPLATE} ..."
          spack install --fail-fast --source --no-check-signature 2>&1 | tee log.install.${ENVNAME}.all
          spack buildcache create -u local-binary

          # Remove binary cache for next round of concretization
          if [ "$USE_BINARY_CACHE" = true ] ; then
            spack mirror rm local-binary
          fi

          # Remove buildcache config settings
          spack config remove config:install_tree:padded_length

          # Next steps: synchronize source and build cache to a central/combined mirror?

          # Cleanup
          spack clean -a
          spack env deactivate

        done
    - name: create-env
      run: |
        # Set up spack-stack
        source ./setup.sh
        export BUILDCACHE_ENVNAME=ue-gcc-11.4.0-buildcache
        export BUILDCACHE_ENVDIR=$PWD/envs/${BUILDCACHE_ENVNAME}
        export ENVNAME=ue-gcc-11.4.0
        export ENVDIR=$PWD/envs/${ENVNAME}
        rsync -av --exclude='install' --exclude='spack.lock' --exclude='.spack_db' ${BUILDCACHE_ENVDIR}/ ${ENVDIR}/
        spack env activate ${ENVDIR}

        # Concretize and check for duplicates
        spack concretize --force 2>&1 | tee log.concretize.${ENVNAME}
        ${SPACK_STACK_DIR}/util/show_duplicate_packages.py -i fms -i crtm -i crtm-fix -i esmf -i mapl -i py-cython -i neptune-env

        # Add binary cache back in
        spack mirror add local-binary file://${BUILD_CACHE_PATH}/
        echo "Packages in combined spack build caches:"
        spack buildcache list

        # Install from cache
        spack install --fail-fast --source --no-check-signature 2>&1 | tee log.install.${ENVNAME}.all

        # Check shared libraries
        ${SPACK_STACK_DIR}/util/ldd_check.py $SPACK_ENV 2>&1 | tee log.ldd_check

        # Create modules
        spack clean -a
        spack module tcl refresh -y
        spack stack setup-meta-modules
        spack env deactivate

        # Test environment chaining
        echo "Test environment chaining"
        spack stack create env --name chaintest --template empty --site linux.default --compiler gcc --upstream ${ENVDIR}/install
        # Retain config from upstream so we don't have to rebuild:
        cp -r ${ENVDIR}/{site,common} $PWD/envs/chaintest/.
        spack env activate ${PWD}/envs/chaintest
        spack add nccmp@1.9.0.1%gcc
        spack concretize | tee envs/chaintest/log.concretize
        unwanted_duplicates=$(( cat envs/chaintest/log.concretize | grep -E '^ - ' | grep -Fv 'nccmp@1.9.0.1' || true ) | wc -l)
        if [ ${unwanted_duplicates} -gt 0 ]; then echo "Environment chaining test failed"; exit 1; fi
        spack env deactivate
        echo "Verify 'create env' warnings"
        echo "# nothing" >> ${SPACK_STACK_DIR}/envs/chaintest/site/packages.yaml
        echo "# nothing" >> ${SPACK_STACK_DIR}/envs/chaintest/common/packages.yaml
        spack stack create env --name chaintest3 --site linux.default --compiler gcc --upstream ${SPACK_STACK_DIR}/envs/chaintest/install 2>&1 | tee stderr.txt
        cnt=$(grep -c "WARNING.*do not match" stderr.txt || true)
        if [ $cnt -lt 3 ]; then echo "Missing 'create env' warnings"; exit 1; fi
    - name: test-env
      run: |
        source /etc/profile.d/modules.sh
        module use /home/ubuntu/spack-stack/modulefiles

        export ENVNAME=ue-gcc-11.4.0
        export ENVDIR=$PWD/envs/${ENVNAME}
        ls -l ${ENVDIR}/install/modulefiles/Core

        module use ${ENVDIR}/install/modulefiles/Core
        module load stack-gcc/11.4.0
        module load stack-openmpi/5.0.8
        module available

        module load jedi-ufs-env
        module load ewok-env
        module load soca-env
        module list
    ssh:
      remoteHost: ${{inputs.resource.ip}}
'on':
  execute:
    inputs:
      resource:
        label: Workflow Target
        type: compute-clusters
        autoselect: true
        optional: false
      gh_org:
        label: GitHub organization/owner
        type: string
        default: jcsda
      gh_repo:
        label: GitHub repository
        type: string
        default: spack-stack
      gh_branch:
        label: GitHub branch
        type: string
        default: feature/update_to_spack_v1
